Eingabemaske Schicht
GeoWerkstatt/ews-boda pull request #159
Opened 2022-07-28 16:15 UTC by MiraGeowerkstatt

#24

2022-07-28 16:47 UTC, danjov requested changes
Q: Muss die Doku nachgeführt werden?

2022-07-28 16:47 UTC, danjov commented on src/Controllers/SchichtController.cs
> +    }
Q: Müssen diese Methoden überschrieben werden oder geht es auch ohne?

2022-07-28 16:47 UTC, danjov commented on tests/BohrprofilControllerTest.cs
> +    private HttpClient httpClient;
REQ: Der `HttpClient` wird nirgends verwendet und kann weg.

2022-07-28 16:47 UTC, danjov commented on tests/BohrprofilControllerTest.cs
> +    private EwsContext context;
REQ: Der `EwsContext` wird nirgends verwendet und kann weg.

2022-07-28 16:47 UTC, danjov commented on src/Controllers/SchichtController.cs
> +public class SchichtController : EwsControllerBase<Schicht>
REQ: Tests fehlen.

2022-07-29 06:54 UTC, MiraGeowerkstatt commented on src/Controllers/SchichtController.cs
> +public class SchichtController : EwsControllerBase<Schicht>
Wollen wir hier auf das Modell "Schicht" zugeschnittene Tests, auch wenn wir nur den Basecontroller ohne weitere Logik nutzen?

2022-07-29 06:55 UTC, danjov commented on src/Controllers/SchichtController.cs
> +public class SchichtController : EwsControllerBase<Schicht>
Ja, ein zwei simple Tests wären nicht verkehrt.

2022-07-29 08:28 UTC, danjov approved these changes

2022-07-29 08:30 UTC, merged