Export data_export db view into a comma-separated file format
GeoWerkstatt/ews-boda pull request #57
Opened 2022-07-04 05:38 UTC by flenny

#18

2022-07-04 06:39 UTC, danjov requested changes
REQ: Den Datenexport muss noch kurz in der Online-Hilfe beschrieben werden. Der Text kann in den bestehenden Artikel _Einstiegsseite_ eingefügt werden.

Ansonsten 👍🏻

2022-07-04 06:42 UTC, danjov commented on src/ClientApp/src/components/Layout.js
> +            <ListItemButton component="a" target="_blank" href="/export">
PP: Simpler Cypress Test für den Export fehlt. Ich denke ein sinnvoller Testfall wäre zu prüfen, ob beim Klick auf Export der Content korrekt als CSV daherkommt.

2022-07-05 06:26 UTC, danjov approved these changes

2022-07-05 06:26 UTC, danjov commented on .gitignore
> +# Cypress test ouput
PP: Typo fixen
```suggestion
# Cypress test output
```

2022-07-05 06:26 UTC, danjov commented on docs/articles/einstiegsseite.md
> +Unter dem Menupunkt _Daten exportieren_ ![Daten exportieren](../images/file-download-icon.png) können die Daten in eine Textdatei mit kommagetrennten Werten (CSV) exportiert und heruntergeladen werde
PP: Typo fixen
```suggestion
Unter dem Menüpunkt _Daten exportieren_ ![Daten exportieren](../images/file-download-icon.png) können die Daten in eine Textdatei mit kommagetrennten Werten (CSV) exportiert und heruntergeladen werden. Die exportierten Felder entsprechen denen der Datenbank View _bohrung.data_export_. Die in UTF-8 codierten Daten können anschliessend, bspw. in Excel unter _Daten_ -> _Aus Text/CSV_ geladen werden.
```

2022-07-05 06:40 UTC, MiraGeowerkstatt approved these changes

2022-07-05 06:47 UTC, danjov requested changes
REQ: CI-Build schlägt fehl.

2022-07-05 08:07 UTC, danjov approved these changes

2022-07-05 08:28 UTC, merged