Eingabemaske standort
GeoWerkstatt/ews-boda pull request #59
Opened 2022-07-05 08:19 UTC by MiraGeowerkstatt

- Achtung! Standorte die mehr als 0 Bohrungen enthalten können im aktuellen Zustand nicht editiert werden, das liegt daran dass es noch ein Problem  mit unseren Datenrelations gibt, das würde ich aber in einem separaten PR lösen.

- Der Einstieg zum Editieren, Löschen und Hinzufügen von Standorten ist derzeit nur über die Standorte-Tabelle möglich (siehe Screenshot), es muss also zunächst gesucht werden. Am besten schauen wir schnell zusammen an wo sonst der geeignete Einstiegspunkt wäre.

![image](https://user-images.githubusercontent.com/49144408/177282894-083e5c94-727e-4223-84c2-e8fad60d2277.png)

2022-07-05 11:27 UTC, danjov requested changes
REQ: Die neuen Dateien im `docs`-Ordner sind vermutlich aus Versehen drin und sollten aus den Changes ausgeschlossen werden.

2022-07-05 11:27 UTC, danjov commented on src/Controllers/StandortController.cs
> +            return new NotFoundResult();
PP: Ich denke das kann vereinfacht werden zu:
```suggestion
            return NotFound();
```

2022-07-05 11:27 UTC, danjov commented on src/Controllers/StandortController.cs
> +            return new NotFoundResult();
PP: Ich denke das kann vereinfacht werden zu:
```suggestion
            return NotFound();
```

2022-07-05 11:27 UTC, danjov commented on tests/StandortControllerTest.cs
> +    private readonly string testStandortBezeichnung = "Blue Jeans Pelati";
PP: Da dieser Wert nie ändert, kann man daraus eine Konstante machen:
```suggestion
    private const string TestStandortBezeichnung = "Blue Jeans Pelati";
```

2022-07-05 11:27 UTC, danjov commented on tests/StandortControllerTest.cs
> +
PP: Der Testfall, wenn man einen ungültigen Standort (zB ohne Beschreibung) versucht zu speichern, wäre auch interessant.

2022-07-05 12:38 UTC, MiraGeowerkstatt commented on src/ClientApp/src/components/DetailMap.js
> +  }, [map]);
Rebase Fehler :(

2022-07-05 12:43 UTC, MiraGeowerkstatt commented on src/ClientApp/src/components/InfoButtonControl.js
> +import React from "react";
Rebase Fehler :(

2022-07-05 12:44 UTC, MiraGeowerkstatt commented on src/ClientApp/src/components/InputForm.js
> +          Umwelt (Afu) freigegeben werden.
Habe den Absatz ganz rausgelassen, da wir noch unklar sind wann das mit der Freigabe relevant wird (nur beim Hinzufügen oder auch beim Editieren).

2022-07-06 09:56 UTC, danjov requested changes

2022-07-06 09:56 UTC, danjov commented on docs/articles/einstiegsseite.md
> +Durch Klicken auf den Button 'Neuen Standort hinzufügen' wird ein Dialog geöffnet, in dem ein neuer Standort angelegt werden kann. Hier können die folgenden Felder befüllt werden.
PP: Markdown Formatierungen für Menüpunkte, Buttons etc. verwenden. Hier als Beispiel:
```suggestion
Durch Klicken auf den Button _Neuen Standort hinzufügen_ wird ein Dialog geöffnet, in dem ein neuer Standort angelegt werden kann. Hier können die folgenden Felder befüllt werden.
```

2022-07-06 09:56 UTC, danjov commented on docs/articles/einstiegsseite.md
> +- User bei der Erstellung
PP: _Benutzer_ oder _Benutzername_ anstatt _User_ als Begriff verwenden. Vorschlag:
* Erstellungsdatum
* Benutzername bei Erstellung

2022-07-06 09:56 UTC, danjov commented on docs/articles/einstiegsseite.md
> +- User bei der Mutation
PP: Gleiche Formulierung wir im Kapitel vorher verwenden. Vorschlag:
* Erstellungs- und Mutationsdatum
* Benutzername bei Erstellung und Mutation

2022-07-06 09:56 UTC, danjov commented on docs/articles/einstiegsseite.md
> +- User bei der Freigabe durch das AfU
PP:
```suggestion
- Benutzername bei der Freigabe durch das AfU
```

2022-07-06 09:56 UTC, danjov commented on src/ClientApp/src/components/DetailMap.js
> +  }, [map]);
REQ: Der Layer ist doppelt drin und kann raus.

2022-07-06 09:56 UTC, danjov commented on src/ClientApp/src/components/InputForm.js
> +                  helperText={error ? "Geben Sie einen Benutzer ein" : ""}
Q: Stimmt dieser Text (noch)?

2022-07-06 09:56 UTC, danjov commented on src/EwsContext.cs
> +        internal int SaveChangesWithoutUpdates()
PP: Ohne Kontext versteht man `WithoutUpdates` nicht ganz. Vorschläge:
* `SaveChangesWithoutUpdatingChangeInformation()`
* `SaveChangesWithoutChangeInformationUpdate()`

2022-07-06 09:56 UTC, danjov commented on src/EwsContext.cs
> +        /// Allows to call <see cref="SaveChanges" /> without override.
PP: Einen aussagekräftigeren Text verwenden, der erwähnt, dass die Änderungsinfos nicht aktualisiert werden.

2022-07-06 09:56 UTC, danjov commented on tests/StandortControllerTest.cs
> +#pragma warning restore CS8625 // Cannot convert null literal to non-nullable reference type.
REQ: Anstatt `CS8625` hier abzuschalten kann man hier den _null-forgiving operator_ verwenden:
```suggestion
        standortToEdit.Bezeichnung = null!;
```

Aber: Ich denke `CS8625` wäre ein Kandidat, den wir in den Testprojekten abstellen können. Im `*.csproj`-File des Testprojekts muss `NoWarn` entsprechend erweitert werden:
```xml
<NoWarn>$(NoWarn),CA1014,CS8625</NoWarn>
```

2022-07-06 11:19 UTC, danjov approved these changes

2022-07-06 11:22 UTC, danjov approved these changes

2022-07-06 11:26 UTC, merged