Afu standort freigabe
GeoWerkstatt/ews-boda pull request #77
Opened 2022-07-12 13:43 UTC by flenny

#68

2022-07-13 08:12 UTC, MiraGeowerkstatt approved these changes

2022-07-13 08:12 UTC, MiraGeowerkstatt submitted a review, later dismissed

2022-07-13 08:12 UTC, MiraGeowerkstatt commented on src/ClientApp/src/components/StandortInputForm.js
> +            defaultValue={GemeindenMap[standort.gemeinde]}
Q: Hattest du nie probleme bei re-rendering?

2022-07-14 08:06 UTC, danjov requested changes
REQ: Dokumentation bezüglich der Freigabe von Standorten ergänzen.

2022-07-14 08:06 UTC, danjov commented on tests/EwsContextTest.cs
> +[System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "Code readability")]
REQ: Die Rule `CA2000` kann global im Testprojekt abgeschaltet werden. Ist meiner Meinung nach in Testprojekten nicht sinnvoll.

2022-07-15 06:08 UTC, danjov requested changes

2022-07-15 06:08 UTC, danjov commented on .editorconfig
> +dotnet_diagnostic.CA2000.severity = none
REQ: Wird die Rule so nicht für alle Projekte abgeschaltet? Falls ja, muss die Rule direkt in `*.csproj`-File des Testprojekts abgeschaltet werden.

2022-07-15 08:39 UTC, danjov approved these changes

2022-07-15 10:15 UTC, merged